# Generated by Django 3.0.3 on 2020-10-15 11:35

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[

            ],
        ),
    ]
