# Generated by Django 3.0.3 on 2020-10-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authentication_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
