name: django_motion
dependencies:
  - python=3.8
  - psycopg2
  - pip
  - pip:
      - django==3.0.3
      - djangorestframework==3.11.0
      - djangorestframework_simplejwt==4.4.0
      - django-filter==2.2.0
      - django-cors-headers
      - coreapi==2.3.3
      - Markdown==3.2.1
      - Pygments==2.5.2
      - gunicorn
      - flake8
